<?php

namespace App\Http\Livewire\Datatables;

use App\Models\Provider;
use App\Models\ProviderPack;
use Mediconesystems\LivewireDatatables\Column;
use Mediconesystems\LivewireDatatables\DateColumn;
use Mediconesystems\LivewireDatatables\Http\Livewire\LivewireDatatable;
use Mediconesystems\LivewireDatatables\NumberColumn;

class PackTable extends LivewireDatatable
{
    public $hideable = 'inline';
    public $exportable = false;
    public $add = true;
    public $add_link = 'pack.create';
    public $permission = 'add provider pack';
    public $providers;

    public function mount($model = false, $include = [], $exclude = [], $hide = [], $dates = [], $times = [], $searchable = [], $sort = null, $hideHeader = null, $hidePagination = null, $perPage = null, $exportable = false, $hideable = false, $beforeTableSlot = false, $buttonsSlot = false, $afterTableSlot = false, $params = [])
    {
        $this->providers = Provider::where('is_service_provider',true)->get();
        parent::mount($model, $include, $exclude, $hide, $dates, $times, $searchable, $sort, $hideHeader, $hidePagination, $perPage, $exportable, $hideable, $beforeTableSlot, $buttonsSlot, $afterTableSlot, $params); // TODO: Change the autogenerated stub
    }


    public function builder()
    {
        //
        return ProviderPack::query()
            ->leftJoin('providers', 'providers.id', 'provider_packs.provider_id')
            ->select('providers.name as provider_name')
            ->groupBy('provider_packs.id');
    }

    public function columns()
    {
        //
        $columns = [
            Column::checkbox(),
            NumberColumn::name('Id')->label('ID')->filterable(),
            Column::name('name')->searchable(),
            Column::name('count'),
            Column::name('price'),
            Column::name('bonus'),
            Column::name('providers.name')->label('Provider')->filterable($this->providers->pluck('name')->toArray())->filterOn('providers.name'),
            DateColumn::name('created_at')->filterable(),
            Column::callback(['id','name'], function ($id,$name) {
                return view('livewire.table-actions.provider-pack-table-actions', ['id' => $id,'item' => ProviderPack::find($id)]);
            })->unsortable()
        ];

        return $columns;

    }
}
